spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    orderTopic: "order-topic"
    orderGroupId: "order-group-id"
    orderStatusTopic: "order-status-topic"
    orderStatusGroupId: "order-status-group-id"

server:
  port: 8082